// FETCH DATA
export const FETCH_DATA_REQUEST = 'FETCH_DATA_REQUEST'
export const FETCH_DATA_SUCCESS = 'FETCH_DATA_SUCCESS'
export const FETCH_DATA_FAILURE = 'FETCH_DATA_FAILURE'
export const CHANGE_THEME = 'CHANGE_THEME'
export const CHANGE_GROUP_ORDER = 'CHANGE_GROUP_ORDER'


